# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://challenge.swisscyberstorm.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: "Swiss Cyber Storm 2015 Security Challenge" 
  avatar: SCS_Logo.png
  gravatar: # email md5 hash
  description: "Swiss Cyber Storm 2015 Challenge, European Cyber Security Challenge, Cyber Security Challenge" # used by search engines
  
  # Header and footer text

  home_text: Home

  header_img: glasses_bg.jpg

  header_text: >
      <img src="/img/SCS_Logo.png" alt="Swiss Cyber Storm Logo">
    
  call_out: >
      <a class="button-inverted" href="https://www.hacking-lab.com/events/registerform.html?eventid=824&uk=iZfqbdtpKitwXJsPfoowycK1RTs2MDhH">
      Register for the 2015 competition!
      </a>

  footer_text: >
      <p>&copy; 2015 Swiss Cyber Storm - Hosting provided by <a href="https://www.nine.ch/en/">nine.ch</a></p>
  
  # Icons
  rss: false
  email_address: # full email address, e.g. "sam@example.com"
  behance:
  bitbucket: 
  dribbble: 
  facebook: "SwissCyberStorm"
  flickr: 
  github:
  google_plus: 
  instagram: 
  linkedin:  # full URL
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange:  # full URL
  steam: 
  tumblr: 
  twitter: "swisscyberstorm"
  wordpress: 
  youtube: 
  
  # Scripts
  google_analytics: # tracking id, e.g. "UA-000000-01"
  disqus_shortname:
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"
  
  # Colors, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "/News/Blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
